use crate::parser::parse_file;
use anyhow::{anyhow, Context, Result};
use app_core::{Frontmatter, Prompt};
use chrono::Utc;
use notify::{RecommendedWatcher, RecursiveMode, Watcher};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::mpsc::{channel, Sender};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};
use walkdir::WalkDir;

/// Events emitted by an `FsPromptStore` watcher.
#[derive(Debug, Clone)]
pub enum Event {
    /// One or more files under the prompts root changed; consumer should re-`list()`.
    Reloaded,
}

/// Guard returned by [`FsPromptStore::watch`]. Dropping it stops the watcher thread
/// (by dropping the underlying `notify` watcher, which closes the internal channel).
pub struct WatchHandle {
    _watcher: RecommendedWatcher,
    _thread: thread::JoinHandle<()>,
}

/// TTL window during which post-`touch()` events for a given path are suppressed.
/// Slightly larger than the watcher debounce so all rename-family events from a
/// single touch (Linux inotify emits `Name(To)` AND `Name(Both)` for the same op)
/// land inside the window.
const SUPPRESS_TTL: Duration = Duration::from_millis(500);

/// Filesystem-backed prompt store rooted at a directory containing `*.md` files.
#[derive(Debug, Clone)]
pub struct FsPromptStore {
    root: PathBuf,
    /// Paths that `touch()` has just rewritten, with their suppression deadlines.
    /// The watcher skips events whose paths are all in this map and not expired.
    /// Bounded in size by the number of in-flight touches (typically 1).
    pending_self_writes: Arc<Mutex<HashMap<PathBuf, Instant>>>,
}

impl FsPromptStore {
    /// Open a store at `root`. Creates `root` if it doesn't exist.
    pub fn new(root: PathBuf) -> Result<Self> {
        if !root.exists() {
            std::fs::create_dir_all(&root).with_context(|| format!("mkdir {}", root.display()))?;
        }
        Ok(Self {
            root,
            pending_self_writes: Arc::new(Mutex::new(HashMap::new())),
        })
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Snapshot every parseable prompt under `root`. Best-effort: files that fail to parse
    /// are logged and skipped (we don't want one malformed file to nuke the launcher).
    pub fn list(&self) -> Vec<Prompt> {
        let mut out = Vec::new();
        for entry in WalkDir::new(&self.root)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.file_type().is_file())
            .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some("md"))
        {
            match parse_file(&self.root, entry.path()) {
                Ok(Some(p)) => out.push(p),
                Ok(None) => {}
                Err(e) => tracing::warn!("skip {}: {e:#}", entry.path().display()),
            }
        }
        out
    }

    /// Find the prompt with `id` and atomically rewrite its file with `last_used = now`.
    ///
    /// The rewritten path is recorded in `pending_self_writes` with a [`SUPPRESS_TTL`]
    /// deadline so an active [`watch`] swallows the resulting filesystem events —
    /// touching a prompt should not cause the consumer to re-poll, since the visible
    /// prompt set hasn't changed.
    pub fn touch(&self, id: &str) -> Result<()> {
        let prompt = self
            .list()
            .into_iter()
            .find(|p| p.id == id)
            .ok_or_else(|| anyhow!("no prompt with id {id}"))?;
        let mut fm = prompt.frontmatter.clone();
        fm.last_used = Some(Utc::now());

        // Pre-register the path (and its canonical form, in case notify reports either)
        // with a TTL. Linux inotify can fire 2+ events for one rename; the TTL covers
        // them all without us having to count event types per OS.
        let deadline = Instant::now() + SUPPRESS_TTL;
        let canon = std::fs::canonicalize(&prompt.path).unwrap_or_else(|_| prompt.path.clone());
        {
            let mut guard = self.pending_self_writes.lock().expect("poisoned");
            guard.insert(prompt.path.clone(), deadline);
            guard.insert(canon, deadline);
            // Opportunistic GC of expired entries so the map can't grow unbounded if
            // a `touch()` happens without an active watcher.
            let now = Instant::now();
            guard.retain(|_, d| *d > now);
        }
        write_atomic(&prompt.path, &fm, &prompt.body)?;
        Ok(())
    }

    /// Spawn a background thread that re-emits a single [`Event::Reloaded`] to `sink`
    /// after 200ms of filesystem-event quiet. Returns a [`WatchHandle`]; dropping the
    /// handle stops the watcher.
    ///
    /// Events generated by [`touch`] on this store are suppressed via the
    /// `pending_self_writes` registry, so a touch does not cause the consumer to
    /// re-poll.
    pub fn watch(&self, sink: Sender<Event>) -> Result<WatchHandle> {
        let (raw_tx, raw_rx) = channel::<notify::Result<notify::Event>>();
        let mut watcher: RecommendedWatcher =
            notify::recommended_watcher(raw_tx).context("create watcher")?;
        watcher
            .watch(self.root.as_path(), RecursiveMode::Recursive)
            .context("watch root")?;

        let pending = Arc::clone(&self.pending_self_writes);

        let handle = thread::Builder::new()
            .name("prompt-store-watch".to_string())
            .spawn(move || {
                const DEBOUNCE: Duration = Duration::from_millis(200);
                loop {
                    // Block for the first *relevant* event. Skip our own tmp files
                    // and events whose paths are all in `pending_self_writes`
                    // (drained as they're consumed, so each touch is suppressed once).
                    loop {
                        match raw_rx.recv() {
                            Err(_) => return, // watcher dropped
                            Ok(Ok(ev)) if event_is_relevant(&ev, &pending) => break,
                            Ok(_) => continue, // tmp-file / self-write / watcher error; ignore
                        }
                    }
                    // Drain extras within the debounce window. Same filter applies so
                    // a touch lurking inside a real burst doesn't extend the window.
                    let deadline = Instant::now() + DEBOUNCE;
                    loop {
                        let remaining = deadline.saturating_duration_since(Instant::now());
                        if remaining.is_zero() {
                            break;
                        }
                        match raw_rx.recv_timeout(remaining) {
                            Ok(_) => continue, // got another event, keep draining
                            Err(_) => break,   // timeout -> quiet -> emit
                        }
                    }
                    if sink.send(Event::Reloaded).is_err() {
                        return; // consumer dropped
                    }
                }
            })
            .context("spawn watch thread")?;

        Ok(WatchHandle {
            _watcher: watcher,
            _thread: handle,
        })
    }
}

/// Serialize a YAML frontmatter block + body and atomically rewrite the file
/// (write to a hidden sibling tmp, then `rename` — survives crashes mid-write).
///
/// The tmp filename is `.<basename>.tmp` (hidden, leading dot) so it doesn't
/// surface to a `~/.prompts/` browser and doesn't shape-match the `*.md` walker.
/// On `rename` failure the tmp file is best-effort cleaned up so failed touches
/// don't leave orphans behind in the prompts dir.
fn write_atomic(path: &Path, frontmatter: &Frontmatter, body: &str) -> Result<()> {
    let yaml = serde_yaml::to_string(frontmatter).context("serialize frontmatter")?;
    let mut out = String::new();
    out.push_str("---\n");
    out.push_str(&yaml);
    if !yaml.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("---\n");
    out.push_str(body);

    let tmp = tmp_sibling(path);
    std::fs::write(&tmp, out.as_bytes()).with_context(|| format!("write tmp {}", tmp.display()))?;
    if let Err(e) = std::fs::rename(&tmp, path) {
        // Best-effort cleanup so failed touches don't leave orphan tmp files behind.
        let _ = std::fs::remove_file(&tmp);
        return Err(e).with_context(|| format!("rename {} -> {}", tmp.display(), path.display()));
    }
    Ok(())
}

/// Compute the hidden sibling path used by [`write_atomic`]: `<parent>/.<basename>.tmp`.
/// Used by the watcher to filter out our own touch events.
fn tmp_sibling(path: &Path) -> PathBuf {
    let parent = path.parent().unwrap_or_else(|| Path::new(""));
    let name = path
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("prompt.md");
    parent.join(format!(".{name}.tmp"))
}

/// True if `path` looks like the hidden tmp file `write_atomic` produces.
/// Used to skip spurious `Event::Reloaded` emissions during a touch.
fn is_our_tmp_file(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|s| s.to_str()) else {
        return false;
    };
    name.starts_with('.') && name.ends_with(".tmp")
}

/// True if at least one path in the event is NOT in `pending_self_writes` (and
/// not our hidden tmp file), AND the event kind represents an actual mutation
/// rather than a read. Used to decide whether to emit `Event::Reloaded`.
///
/// Suppression is TTL-based, not consume-once: a single `touch()` may produce
/// 2+ rename-family events on Linux inotify (`Name(To)` AND `Name(Both)` for
/// the same op), so we leave the entry in place until [`SUPPRESS_TTL`] expires.
fn event_is_relevant(ev: &notify::Event, pending: &Mutex<HashMap<PathBuf, Instant>>) -> bool {
    // Access events (Open / Close / Read) are not content changes; a re-list would
    // produce identical output. Ignore them.
    if matches!(ev.kind, notify::EventKind::Access(_)) {
        return false;
    }
    if ev.paths.is_empty() {
        // No paths means we can't filter — treat as relevant to avoid silent drops.
        return true;
    }
    let guard = pending.lock().expect("poisoned");
    let now = Instant::now();
    let path_is_suppressed = |p: &Path| -> bool {
        if is_our_tmp_file(p) {
            return true;
        }
        if guard.get(p).is_some_and(|d| *d > now) {
            return true;
        }
        if let Ok(canon) = std::fs::canonicalize(p) {
            if guard.get(&canon).is_some_and(|d| *d > now) {
                return true;
            }
        }
        false
    };
    !ev.paths.iter().all(|p| path_is_suppressed(p.as_path()))
}
